<?php

return [
    'ROCKET_CHAT_API_BASE_URL' => env('ROCKET_CHAT_API_BASE_URL', ''),
    'ROCKET_CHAT_AUTH_TOKEN' => env('ROCKET_CHAT_AUTH_TOKEN', ''),
    'ROCKET_CHAT_USER_ID' => env('ROCKET_CHAT_USER_ID', ''),
];
